name: valence
description: "Habit Tracker app with collaboration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI Components
  flutter_colorpicker: ^1.0.3
  great_list_view: ^0.2.3
  animated_reorderable_list: ^1.3.0
  fl_chart: "^1.1.1"
  simple_heatmap_calendar: ^0.4.0
  flutter_donation_buttons: ^0.4.8

  # Extra Features
  dynamic_color: ^1.5.4
  material_color_utilities: ^0.11.1
  linked_scroll_controller: ^0.2.0
  sliver_tools: ^0.2.9
  share_plus: ^12.0.1
  file_selector: ^1.0.3
  path_provider: ^2.0.14
  device_info_plus: ^12.3.0
  flutter_local_notifications: ^21.0.0
  flutter_svg: ^2.0.4
  flutter_timezone: ^5.0.1
  markdown_widget: ^2.3.2+8
  url_launcher: ^6.1.10
  package_info_plus: ^9.0.0
  copy_with_extension: ^14.0.0
  json_annotation: ^4.9.0
  win2iana_tz_converter: ^0.1.3
  open_file: ^3.5.10
  app_settings: ^7.0.0

  # Fonts and Icons
  named_html_color: ^0.0.3+1
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  cryptofont: ^1.0.2+1
  phosphor_flutter: ^2.1.0
  google_fonts: ^6.2.1

  # Data Structure
  provider: ^6.0.5
  tuple: ^2.0.1
  quiver: ^3.2.1
  uuid: ^4.1.0
  collection: ^1.17.0
  crypto: ^3.0.2
  timezone: ^0.11.0
  nested: ^1.0.0
  async: ^2.11.0
  pool: ^1.5.1

  # Data Persistence
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  sqflite_common_ffi: ^2.3.0+4
  path: ^1.8.2

  # Animation
  animated_check: ^1.0.5
  animations: ^2.0.7

  # logging
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  flutter_lints: ^6.0.0
  test: ^1.21.4
  test_cov_console: ^0.2.2
  mockito: ^5.4.4

  # Code Generation
  build_runner: ^2.3.3
  copy_with_extension_gen: ^14.0.0
  icon_font_generator:
    git:
      url: https://github.com/Gaurav192/icon_font_generator.git
      ref: file_path_fix
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.6.1
  source_gen: ^4.2.2

  # Utilities
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - LICENSE
    - LICENSE_THIRDPARTY.md
    - CHANGELOG.md
    - docs/CHANGELOG/
    - PRIVACY.md
    - configs/about_info.json
    - configs/contributors.json
    - assets/sql/
    - assets/images/
    - assets/logo/icon-momo.svg

  generate: true

  fonts:
    - family: HabitSortIcons
      fonts:
        - asset: assets/fonts/sort_icons.ttf
    - family: HabitCalIcons
      fonts:
        - asset: assets/fonts/cal_icons.ttf
    - family: HabitProgressIcons
      fonts:
        - asset: assets/fonts/progress_icons.ttf
    - family: CommonIcons
      fonts:
        - asset: assets/fonts/common_icons.ttf
    - family: Obviously
      fonts:
        - asset: assets/fonts/Obviously-Bold.otf
          weight: 700
        - asset: assets/fonts/Obviously-SemiBold.otf
          weight: 600

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true
    lottie: true
