// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPyk2-ReJA3JqKtkipLaOba40_Wxvpwk',
    appId: '1:191839563310:web:a30fe7862620426dd3f9bf',
    messagingSenderId: '191839563310',
    projectId: 'valence-958c2',
    authDomain: 'valence-958c2.firebaseapp.com',
    storageBucket: 'valence-958c2.firebasestorage.app',
    measurementId: 'G-6JE9BP2G5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINZ0nRWc17Ok34kxMxLFsMZpctgFpaII',
    appId: '1:191839563310:android:8da1a6b8b0d184a5d3f9bf',
    messagingSenderId: '191839563310',
    projectId: 'valence-958c2',
    storageBucket: 'valence-958c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXpZ-Kvsjq1ghXLfOX4ROnzzhn3hzMqIs',
    appId: '1:191839563310:ios:b109b7424f833be3d3f9bf',
    messagingSenderId: '191839563310',
    projectId: 'valence-958c2',
    storageBucket: 'valence-958c2.firebasestorage.app',
    iosClientId: '191839563310-i23ij31uhnbe60f18tuuap2h2tfbodmg.apps.googleusercontent.com',
    iosBundleId: 'me.pranaovs.valence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXpZ-Kvsjq1ghXLfOX4ROnzzhn3hzMqIs',
    appId: '1:191839563310:ios:b109b7424f833be3d3f9bf',
    messagingSenderId: '191839563310',
    projectId: 'valence-958c2',
    storageBucket: 'valence-958c2.firebasestorage.app',
    iosClientId: '191839563310-i23ij31uhnbe60f18tuuap2h2tfbodmg.apps.googleusercontent.com',
    iosBundleId: 'me.pranaovs.valence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlPyk2-ReJA3JqKtkipLaOba40_Wxvpwk',
    appId: '1:191839563310:web:3abf4331f756a123d3f9bf',
    messagingSenderId: '191839563310',
    projectId: 'valence-958c2',
    authDomain: 'valence-958c2.firebaseapp.com',
    storageBucket: 'valence-958c2.firebasestorage.app',
    measurementId: 'G-G3659DMMLE',
  );
}
